version: '3.8'

services:
  # blue-api:
  #   container_name: blue-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     ENV: local
  #     BASE_URL: http://localhost:3001
  #     PORT: 3001
  #     DB_NAME: blue-api-local
  #     DB_USERNAME:
  #     DB_PASSWORD:
  #   ports: 
  #     - 3001:3001
  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js